### ISSUE TITLE
npm deprecation warnings on build

### ISSUE THREAD

**Issue by loganjohnlong** [LectureGoggles/lecture-goggles-frontend#79]
The following is brought up on build.

> npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
> npm WARN deprecated core-js@2.6.4: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

For security purposes, all of these need to either be updated to the latest version, the latest long-term support version, or have a reason as to why they cannot be updated.

**Comment by NathanYocum** [comment]
Is there a way to updgrade Node and npm on Azure @loganjohnlong?

I believe the issue is because we are running node 8.10.0 and npm 3.5.2, since I don't get the warnings locally using node 11.14.0 and npm 6.9.0

**Comment by loganjohnlong** [comment]
Solved using node 11.14.0 and npm 6.9.0
